### ISSUE TITLE
multiple controllers

### ISSUE THREAD

**Issue by luisbrandao** [gernest/utron#105]
Hey,

Just starting with go and trying to use uton because its look like a little familiar with the little i know.
I am using the todo application to start out but i cant discover hot to add more controllers.

I moved the original todo to a /todo url and tried to make a new controller/model for /myapp. 
The second controller got a bunch of duplicated declaration errors and no route in the second controller worked...
how do i get started in this?

**Comment by nicola-spb** [comment]
Please write errors or it should be closed.
