### ISSUE TITLE
is there an example use router in json file

### ISSUE THREAD

**Issue by nyrf** [gernest/utron#17]
https://github.com/gernest/utron#case-3-using-routes-file
I defined routers in json file, but it not work.

**Comment by gernest** [comment]
@nyrf   yes, see "case 3: using routes file" in the README there is  link to the example file.

**Comment by gernest** [comment]
@nyrf can you show me your code?

**Comment by nyrf** [comment]
I only modified the todo example.

config/routes.json
```go
{
  "routes": [
    "get;/;TODO.Home",
    "post;/create;TODO.Create",
     "get;/delete/{id};TODO.Delete"
  ]
}
```
controllers/todo.go

```go
package controllers

import (
	"net/http"
	"strconv"

	"github.com/gernest/utron"
	"github.com/gernest/utron/fixtures/todo/models"
	"github.com/gorilla/schema"
)

var decoder = schema.NewDecoder()

type TODO struct {
	*utron.BaseController
	Routes []string
}

func (t *TODO) Home() {
	todos := []*models.Todo{}
	t.Ctx.DB.Order("created_at desc").Find(&todos)
	t.Ctx.Data["List"] = todos
	t.Ctx.Template = "index"
	t.HTML(http.StatusOK)
}
func (t *TODO) Create() {
	todo := &models.Todo{}
	req := t.Ctx.Request()
	req.ParseForm()
	if err := decoder.Decode(todo, req.PostForm); err != nil {
		t.Ctx.Data["Message"] = err.Error()
		t.Ctx.Template = "error"
		t.HTML(http.StatusInternalServerError)
		return
	}

	t.Ctx.DB.Create(todo)
	t.Ctx.Redirect("/", http.StatusFound)
}

func (t *TODO) Delete() {
	todoID := t.Ctx.Params["id"]
	ID, err := strconv.Atoi(todoID)
	if err != nil {
		t.Ctx.Data["Message"] = err.Error()
		t.Ctx.Template = "error"
		t.HTML(http.StatusInternalServerError)
		return
	}
	t.Ctx.DB.Delete(&models.Todo{ID: ID})
	t.Ctx.Redirect("/", http.StatusFound)
}
```

**Comment by nyrf** [comment]
Still add this code in toto controller file? thanks.

```go
func NewTODO() *TODO {
	return &TODO{
		Routes: []string{
			"get;/;Home",
			"post;/create;Create",
			"get;/delete/{id};Delete",
		},
	}
}

func init() {
	utron.RegisterController(NewTODO())
}
```

**Comment by gernest** [comment]
@nyrf can you be specific what do you mean  by `it doesn't work"? are you getting errors or? your routes file seems fine. And there is no need to add `Routes` field if you have routes file.

**Comment by nyrf** [comment]
When i visit localhost:8090, got `404 page not found`

**Comment by nyrf** [comment]
I only added `config/routes.json` and modified `controller/todo.go`, then run `go run main.go` and visit `http://localhost:8090`.

**Comment by gernest** [comment]
@nyrf if you remove the routes file does it work?

**Comment by nyrf** [comment]
If remove routes.json file and use 

```go
func NewTODO() *TODO {
    return &TODO{
        Routes: []string{
            "get;/;Home",
            "post;/create;Create",
            "get;/delete/{id};Delete",
        },
    }
}

func init() {
    utron.RegisterController(NewTODO())
}
```
I works.

**Comment by gernest** [comment]
@nyrf okay, I will check this later when I get time.

**Comment by nyrf** [comment]
`https://github.com/nyrf/utron/tree/use-routes-file/fixtures/todo`, this is all my code.

**Comment by nyrf** [comment]
@gernest Thanks for your work.

**Comment by gernest** [comment]
@nyrf  you are welcome.

I just checked on your routes file
```json
{
  "routes": [
    "get;/;TODO.Home",
    "get;/home;TODO.Home",
    "post;/create;TODO.Create",
    "get;/delete/{id};TODO.Delete"
  ]
}
```

Do me a favor and omit registering the same method twice. Overriding support provided by utron is basic, there is a long way to make it stable.

Try changing your routes file to look like this below. Notice I omitted the `/home` route.

```json
{
  "routes": [
    "get;/;TODO.Home",
    "post;/create;TODO.Create",
    "get;/delete/{id};TODO.Delete"
  ]
}
```

Hope it works, either way I will look into into this when I get time.

**Comment by nyrf** [comment]
I deleted ` "get;/home;TODO.Home",` but it still not work.

**Comment by nyrf** [comment]
@gernest Any update?

**Comment by gernest** [comment]
@nyrf I was checking this, you are right. The implementation is basic and incomplete. I advice you use the `Routes` field instead. I really don't have time to reimplement this, so you have to be patient untill when I get time, or until someone help this out.

So far the loading is good(of routes from the file), but I can't come into consesus on the registering of the loaded routes.
