### ISSUE TITLE
@gernest is still not hired

### ISSUE THREAD

**Issue by lstrojny** [gernest/utron#19]
This is a serious bug and must stay open until https://github.com/gernest/utron#are-you-hiring can be removed.

**Comment by thinktainer** [comment]
+1

**Comment by mauri** [comment]
+1

**Comment by Grynn** [comment]
@gernest I am recruiting at Media.Net. I am in need too, in need of good devs. Please send me your skype username and/or phone number and a good time to chat. 

vishal.d@media.net / vishal.doshi@gmail.com

**Comment by Collizo4sky** [comment]
+1

**Comment by mawuli** [comment]
+1 :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by Grynn** [comment]
So there's something not quite right. Media.net is one of the largest advertising tech cos in the world (https://www.quora.com/Which-company-should-I-join-Snapdeal-Directi-Practo-or-Quikr). I offered to interview @gernest sans CV but have not even heard from him. Just sayin.

**Comment by gernest** [comment]
@Grynn I am sorry, I was offline, My skype ID is live:geofreyernest.

Would you please be positive in your comments. A lot of good  people are helping me getting a job by supporting me, so putting negative remarks is not very good.

**Comment by Pym** [comment]
@Grynn yeah, something's not quite right: this kind of remarks. Just sayin.

**Comment by pablocrivella** [comment]
+1

**Comment by dvbeato** [comment]
+1

**Comment by wagnerads** [comment]
+1

**Comment by gabriellhrn** [comment]
+1

**Comment by onlydole** [comment]
+1

**Comment by marcosinger** [comment]
:heart_eyes_cat:

**Comment by christianpv** [comment]
+1

**Comment by bredikhin** [comment]
+1

**Comment by ozkxr** [comment]
:star:

**Comment by rabeesh** [comment]
+1

**Comment by Peekmo** [comment]
:+1:

**Comment by martinpinto** [comment]
+1

**Comment by tylerdmace** [comment]
+1

**Comment by Gurpartap** [comment]
:+1:

**Comment by eolexe** [comment]
+1

**Comment by heshed** [comment]
+1

**Comment by vsouza** [comment]
+1

**Comment by gabrielpugliese-luizalabs** [comment]
+1

**Comment by rogeriomarques** [comment]
+1

**Comment by Mason8r** [comment]
+1
