### ISSUE TITLE
Why not using RESTful urls?

### ISSUE THREAD

**Issue by betoharres** [gernest/utron#21]
Would be the perfect if you implement that.

**Comment by gernest** [comment]
@betoharres can elaborate with examples? RESTful urls is vague , and subjective.

**Comment by betoharres** [comment]
@gernest I meant something like this http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api
and others must-have best practices out of the box. 
That's what advancing the technology is, right? Not reinventing the wheel :)

**Comment by OsvaldoTCF** [comment]
Well, but this is not an api or a restful framework. Why do that?

**Comment by betoharres** [comment]
It's just a suggestion :) that's ok

**Comment by gernest** [comment]
@betoharres I forgot to say that the link you referenced is not framework level implementation detal but application level. You can build a RESTFUL API with utron.
