### ISSUE TITLE
http: multiple response.WriteHeader calls

### ISSUE THREAD

**Issue by nyrf** [gernest/utron#24]
Run `wrk -t12 -c900 -d10s http://localhost:3000`

Got errors `http: multiple response.WriteHeader calls`

**Comment by gernest** [comment]
@nyrf  Please accompany your issues with enough information. What does that suppose to mean?
`http: multiple response.WriteHeader calls` is a result of writting to the response writter more than once.

It is not utron error, check if you are writing to the response more than once.

**Comment by nyrf** [comment]
I have fixed it, thanks.
