### ISSUE TITLE
What is the best way we can create good restful apis with Utron ?

### ISSUE THREAD

**Issue by OsvaldoTCF** [gernest/utron#30]
This is a newbie question.

What is the best way we can create good restful apis with Utron ?

**Comment by gernest** [comment]
It depends on what kind of API you want to implement. The base essence of RESTFUL API's is responding with json.

`utrom`  BaseController has a method `JSON` whuch helps you out by setting the header ad the status code for meaningful json response.

**Comment by gernest** [comment]
@OsvaldoTCF you can follow the same MVC pattern and have a beautufl restful API. take the todo app as an exmple, and rethink if you were to communicate via JSON.

If I get time I will throw up a todo API example. But I'm very busy, you can start and I will help when you face any issue.

**Comment by OsvaldoTCF** [comment]
Thanks
