### ISSUE TITLE
Multiple Controllers

### ISSUE THREAD

**Issue by euller88** [gernest/utron#31]
Hi, I'm a newbie in Golang, and recently discovered this amazing framework that is utron. From now on, I will use it, because it seems much more comfortable to work with than the others I've seen around. But I want to expose this doubt I have. Is a good practice to write one different controller for each service(url) my application offers?

**Comment by gernest** [comment]
@euller88  thank you, it is not necessary. As you can see the example it has only one controller but handles a bunch of urls.

**Comment by euller88** [comment]
@gernest  thank you for your answer and keep up the excellent work.
