### ISSUE TITLE
Default 404 and 500 page with utron

### ISSUE THREAD

**Issue by euller88** [gernest/utron#32]
Hi, how can I write a default response from my server to these errors with utron? For example, if someone tries to access myserver.com/not_a_valide_resource, how can I handle it? Thanks in advance for the help

**Comment by gernest** [comment]
@euller88  Serving 404 or 500 is simple. Just change the status code to the respective value. Take for instance the code snippet from the todo example link [here](https://github.com/gernest/utron/blob/8cb272e7c57acf8deb4cd88463372729bbcc93d3/fixtures/todo/controllers/todo.go#L24).

```go
func (t *TODO) Home() {
	todos := []*models.Todo{}
	t.Ctx.DB.Order("created_at desc").Find(&todos)
	t.Ctx.Data["List"] = todos
	t.Ctx.Template = "index"
	t.HTML(http.StatusOK)
}
```

If you want to return 404 response, just change the last line to

```go
	t.HTML(404)
```

if you want to return 500 response change the last line to

```go
	t.HTML(500)
```

For the record, `http.StatusOk==200` so the status codes are all in the standard library's `http` package. Take your time and check the list of all status code here [https://golang.org/pkg/net/http/#pkg-constants](https://golang.org/pkg/net/http/#pkg-constants)

**Comment by ergoz** [comment]
But what about situation when we have not controller for url and utron shows error message without template? What is correct way to handle this situation?
