### ISSUE TITLE
A more complex example

### ISSUE THREAD

**Issue by OsvaldoTCF** [gernest/utron#36]
I will create a more complex example and would like help. It would be great if we had more examples.

Who can help ... 

https://github.com/OsvaldoTCF/order2go

**Comment by gernest** [comment]
@OsvaldoTCF  hey I am already going throutgh it. When  I get time I will start hacking on it. But you will need to give me more details on what it is and what it is supposed to do.

Or do you need help in specific area?

**Comment by OsvaldoTCF** [comment]
An example involving more problems. More tables and relationships in the database , more restrictions , etc.
I am creating this example is an ordering system .

**Comment by gernest** [comment]
@OsvaldoTCF how is the app going? Would you like it to be added in like examples section in README? If you are still maintaining it let me know.

**Comment by Slacki** [comment]
@OsvaldoTCF I've put your example in this repo wiki. Hope you don't mind.

**Comment by Slacki** [comment]
@gernest I think this issue can be closed now.

**Comment by gernest** [comment]
@Slacki thanks. I am closing it now.

**Comment by euller88** [comment]
@gernest @Slacki Currently, the Order2Go project will be refactored and updated in order to make it a more suitable example for Utron, this may not be soon, but the team asks to not put some unfinished work as reference.

**Comment by Slacki** [comment]
@euller88 Okay, I am removing the refference in Wiki now.
