### ISSUE TITLE
How can I declare Foreign Key?

### ISSUE THREAD

**Issue by OsvaldoTCF** [gernest/utron#37]
How can I declare foreign key on models ?

**Comment by OsvaldoTCF** [comment]
I can use this: `sql:"type:bigint REFERENCES Sponsors(id)"` on model's field declaration but if table "sponsors" will be created after actual table, i get this error: (pq: relation "sponsors" does not exist) 

Is there any form of manage the tables creation order ?

**Comment by OsvaldoTCF** [comment]
How can i issue this command:   "db.Model(property).AddForeignKey("product_id", "products", "CASCADE", "RESTRICT") " from may Utron application?

From GORM

"... it is. Here's a real world example:

    db.Model(property).AddForeignKey("product_id", "products", "CASCADE", "RESTRICT")

phoenix_test=# \d properties;
                                    Table "public.properties"
   Column   |           Type           |                        Modifiers                        
------------+--------------------------+---------------------------------------------------------
 id         | integer                  | not null default nextval('properties_id_seq'::regclass)
 created_at | timestamp with time zone | 
 updated_at | timestamp with time zone | 
 deleted_at | timestamp with time zone | 
 product_id | integer                  | 
 value_id   | integer                  | 
 value_type | character varying        | 
Indexes:
    "properties_pkey" PRIMARY KEY, btree (id)
Foreign-key constraints:
    "properties_product_id_foreign" FOREIGN KEY (product_id) REFERENCES products(id) ON UPDATE RESTRICT ON DELETE CASCADE "

**Comment by gernest** [comment]
@OsvaldoTCF in the contex there is a `DB` property. You can use it to do all of that. It is a full `*gorm.DB` .  see [here](https://github.com/gernest/utron/blob/386b86de909d8101f9ba8cf61445a1de44ce6250/context.go#L54)

**Comment by OsvaldoTCF** [comment]
Thankyou

**Comment by OsvaldoTCF** [comment]
Gernest, what is the best time to run the command to complete the migration? What is the time "after" migration?

**Comment by gernest** [comment]
@OsvaldoTCF Migrations are one time affair. But you can run them as many times as you like, since It wil only create the tables if they don't exist yet.

I recomment you do that before starting the app. I have been a bit busy lately, but when I get time I will look more into this, there is a lot of stuffs to improve.

**Comment by OsvaldoTCF** [comment]
Thank you so much for your help!

**Comment by OsvaldoTCF** [comment]
I open an issue on GORM: Is there any way to force order of creation of the tables?
https://github.com/jinzhu/gorm/issues/725

I need to force the order in which the tables are created to avoid problems with the creation of foreign keys.

**Comment by OsvaldoTCF** [comment]
From GORM:
"Same order as you pass it to the CreateTable, AutoMigrate"

**Comment by OsvaldoTCF** [comment]
utron.go (239)
