### ISSUE TITLE
Need a logo

### ISSUE THREAD

**Issue by gernest** [gernest/utron#38]
Any ideas for a `utron` logo?

**Comment by OsvaldoTCF** [comment]
Bsed on Ultron? ;-)

http://www.google.com.br/imgres?imgurl=http://vignette2.wikia.nocookie.net/marvelmovies/images/b/bc/Ultron_Empire_textless.jpg/revision/latest%3Fcb%3D20150126200212&imgrefurl=http://marvel-movies.wikia.com/wiki/Ultron&h=793&w=640&tbnid=HVhF_evEqg8YbM:&tbnh=186&tbnw=150&usg=__TohwugVvX_8vHYb_U3HqmSBNPd4=&docid=lRxxQkip-g9X-M&itg=1&client=ubuntu

**Comment by gernest** [comment]
@OsvaldoTCF cool. Is the image copyrighted? We need something cool like that.

**Comment by OsvaldoTCF** [comment]
Well, this is the image of the cinema, so I imagine that has copyright. Perhaps a good idea is to use it as a base.

**Comment by euller88** [comment]
Having Ultron as a reference could butthurt someone, and you really doesn't want to be sued by Disney. How about using a robot gopher to be the concept for the logo?

**Comment by gernest** [comment]
@euller88 you are right. So bad that I suck at graphics. A robot gopher will be cooler.

**Comment by gernest** [comment]
@euller88 do you use gitter? We can discuss more about utron there https://gitter.im/gernest/utron

**Comment by paramah** [comment]
Ok guys :) maybe something like that ? 


![ultron](https://cloud.githubusercontent.com/assets/17670/17102608/b747b514-527a-11e6-855c-8df5fc71fa4e.png)

**Comment by paramah** [comment]
gr8 

in zip you have ai,svg and png version. Enjoy :)

[ultron_logo.zip](https://github.com/gernest/utron/files/381595/ultron_logo.zip)
;)

**Comment by paramah** [comment]
ok, i back to my webapp powered by ultron :) thx for gr8 frame ;>

**Comment by gernest** [comment]
@paramah minor detail, what is the purpose of the red line on the gopher fore head. I think it doesnt mix well with gopher

**Comment by gernest** [comment]
If the redline is gone, the gopher looks even more bad ass than utron. :)

**Comment by gernest** [comment]
@paramah Thank you.

**Comment by paramah** [comment]
@gernest hmmm, right. Give me some time i will make some little changes with colors and shapes.

**Comment by gernest** [comment]
Okay, I will just add this for now to see how it looks like. Later you can just update the image and submit a PR for easy contributing.

**Comment by gernest** [comment]
see #63
