### ISSUE TITLE
HTTPS with Utron

### ISSUE THREAD

**Issue by euller88** [gernest/utron#39]
I've seen that to make a HTTPS server with Go, I have to use the ListenAndServeTls instead of the ListenAndServe. But this is only if make the hard work that I don't want to. Utron already do this work for me, so I can worry with others things. But how can I configure Utron to work with HTTPS? Because a quick look doesn't show the use of it, and I am not comfortable to change your code. Thank you in advance for your answer

**Comment by OsvaldoTCF** [comment]
utron.go (242)

func Run() {
	Migrate()
	port := baseApp.cfg.Port
	logThis.Info("starting server at ", baseApp.cfg.BaseURL)
	log.Fatal(http.ListenAndServe(fmt.Sprintf(":%d", port), baseApp))
}

**Comment by OsvaldoTCF** [comment]
We could have something like RunTls to https . A Gin approach.

**Comment by OsvaldoTCF** [comment]
One approach with middleware . Martini.

https://github.com/martini-contrib/secure
martini-secure
==========================
import (
  "github.com/go-martini/martini"
  "github.com/martini-contrib/secure"
)

func main() {
  m := martini.Classic()

  martini.Env = martini.Prod  // You have to set the environment to `production` for all of secure to work properly!

  m.Use(secure.Secure(secure.Options{
    AllowedHosts: []string{"example.com", "ssl.example.com"},
    SSLRedirect: true,
    SSLHost: "ssl.example.com",
    SSLProxyHeaders: map[string]string{"X-Forwarded-Proto": "https"},
    STSSeconds: 315360000,
    STSIncludeSubdomains: true,
    FrameDeny: true,
    ContentTypeNosniff: true,
    BrowserXssFilter: true,
    ContentSecurityPolicy: "default-src 'self'",
  }))
  m.Run()
}

**Comment by euller88** [comment]
I've come with this solution
```Go
func RunTLS() {
	Migrate()
	port := baseApp.cfg.Port
	logThis.Info("starting server at ", baseApp.cfg.BaseURL)
	log.Fatal(http.ListenAndServeTLS(fmt.Sprintf(":%d", port), "cert.pem", "key.pem", baseApp))
}
```
I placed this in utron.go, and now I don't have any problem with https. Also, cert.pem and key.pem were generated with openssl and placed in the executable folder

**Comment by gernest** [comment]
@euller88 cool!
