### ISSUE TITLE
Layouts or blocks in the views

### ISSUE THREAD

**Issue by arschles** [gernest/utron#4]
It would be nice to be able to specify a reusable layout or reusable blocks in the views. As an example, [the Render library](https://github.com/unrolled/render#layouts) does this fairly well. These features would make it easier to build larger sites.

**Comment by gernest** [comment]
That is a good feature, you can pull it yourself easily and use it with `utron`. the view in utron is an interface with the following signature.

```go
type View interface {
	Render(out io.Writer, name string, data interface{}) error
}
```
I think `SimpleView` whish is shipped with `utron` should remain simple. And maybe add a section in the README for different `View` implementation that `utron` users can choose from.

**Comment by influx6** [comment]
Nice work bro, keep it going

**Comment by gernest** [comment]
Thanl you @influx6 and you are welcome to contribute.
