### ISSUE TITLE
Raw Body

### ISSUE THREAD

**Issue by euller88** [gernest/utron#40]
Sorry for the noobness, but how I get the raw body data for a POST or PUT request? Thank you in advance for the answer

**Comment by gernest** [comment]
@euller88 what do you mean by raw body?

**Comment by euller88** [comment]
I think I'm not expressing myself very well. When I try to use utron.BaseController.Ctx.Request().Body(), I've got an empty byte slice from an POST request with content, and this shouldn't happen. So I'm asking what is the right way of doing it, in order to see what I'm doing wrong. Here a sample of what I'm doing:
```go
func (a *MyAction) ReadBody(){
    var body []byte
    _, err := a.Ctx.Request().Body(body)
    if err != nil{
        log.Println(err.Error())
    } else {
        a.Ctx.Write(body)
    }
}
```

**Comment by gernest** [comment]
@euller88  `request.Body` is an `io.Reader` so don't read it like that. You can use `ioutil.ReadAll` instead.

**Comment by euller88** [comment]
Thanks, it was a great help to me.

**Comment by OsvaldoTCF** [comment]
http://jmoiron.net/blog/crossing-streams-a-love-letter-to-ioreader/
