### ISSUE TITLE
Empty environment variables are ignored

### ISSUE THREAD

**Issue by kojustin** [gernest/utron#45]
In some environments I want to use the environment variables to override the default values that are set in a config file. For example, in a test environment I may want to use an empty db user (e.g. pass `DB_USER=""` to a particular command) .

Right now, [config.go](https://github.com/gernest/utron/blob/master/config.go#L127) cannot distinguish between a zero-length environment variable and a environment variable that is not present.

**Comment by gernest** [comment]
@kojustin you can overide the environment variables that are defined in the utron configuration object so if you want to set other arbitrary variables you can easily get them for yourself using `os.GetEnv`

For your example, there is no `DB_USER` in utron configuration object, so you can easily access it somewhere in your code like this

``go
dbUser:=os.GetEnv("DB_USER")
``
and whatever value you set will be in `dbUser` variable.

**Comment by kojustin** [comment]
What if I want to indicate that there is no database password?

**Comment by gernest** [comment]
@kojustin then then enviroonment variable `DATABASE_CONN` is what you are looking for.

**Comment by gernest** [comment]
@kojustin  see here https://github.com/gernest/utron#configurations for more details.

Please let me know if this is helpful.

**Comment by kojustin** [comment]
ok
