### ISSUE TITLE
Disabling Automigration

### ISSUE THREAD

**Issue by euller88** [gernest/utron#46]
Is there a way to disable the automigration of the tables trough some method that utron provides, or I have to do it by changing the source?

**Comment by gernest** [comment]
@euller88 just implemented this, now there is an additional settings in configuration file. You just need to set automigrate to false to disable automigration.

The good news is, you can then automigrate manually anywhere in your application by calling `utron.Migrate()`

This is how the configuration file looks like right now
```json
{
	"app_name": "utron web app",
	"base_url": "http://localhost:8090",
	"port": 8090,
	"verbose": false,
	"static_dir": "fixtures/static",
	"view_dir": "fixtures/view",
	"database": "",
	"database_conn": "",
     "automigrate":true
}
```
