### ISSUE TITLE
Environment configuration

### ISSUE THREAD

**Issue by apaganobeleno** [gernest/utron#5]
@gernest What do you think about reading some config values from the ENV before reading from the config.{ json | yaml | toml } file?

I'm thinking that in some cases **utron** will need different values for the database connection and other configuration elements like the port depending on the environment we're running the app, for example our Production database url will be different than our development/testing URL.

Maybe **utron** could make the app read ENV variables and if these are not satisfied then read from the config file.

Other alternative we could do it provide environment specific configuration in the config.{json | yaml | toml} file, but in some cases reading from the ENV would be needed as well.

Again and as usual, once you agree with one of the alternatives i would be very happy to help.

**Comment by gernest** [comment]
@apaganobeleno  I'm not so sure about this. I mean the second premise of `relevance` is about relevance. And you are right in some aspect.

Would you please implement it and submit a pull request, so I can see your approach and maybe we can improve and comeup with something that wont hurt `utron` ?

**Comment by Gurpartap** [comment]
@gernest I think the proposal here is that we need something like this:

```
todo
├── config
│   └── development
│       └── app.json
│   └── test
│       └── app.json
│   └── production
│       └── app.json
:
```

**Comment by apaganobeleno** [comment]
@gernest @Gurpartap actually i'm thinking we should build the **environment variable override** version because its quite bit simple, and reduces the number of files/parts moving.

Basically we would have the same number of files (p.e. a single app.json) and simply override with ENV based on the environment we are running the app.

thoughts ?

**Comment by apaganobeleno** [comment]
@gernest @Gurpartap in terms of the proposal, i'm thinking we should read the following ENV variables:

- PORT
- DATABASE
- DATABASE_CONN

And in case they are set we will override the values that have been set on the *config/app.json* file.

**Comment by Gurpartap** [comment]
Yes, it's a good idea to allow overriding with environment variables. And since people do not prefer to commit production database url and credentials in their version control repos, it would be easier to pass env vars than to create a file with vars during deployments.

**Comment by gernest** [comment]
@apaganobeleno @Gurpartap  hey, ithink you are right. And infact we can parse dynamically all the fields of the config file from ENV

I mean for this stuct
```go
type Config struct {
	AppName      string `json:"app_name" yaml:"app_name" toml:"app_name"`
	BaseURL      string `json:"base_url" yaml:"base_url" toml:"base_url"`
	Port         int    `json:"port" yaml:"port" toml:"port"`
	Verbose      bool   `json:"verbose" yaml:"verbose" toml:"verbose"`
	StaticDir    string `json:"static_dir" yaml:"static_dir" toml:"static_dir"`
	ViewsDir     string `json:"view_dir" yaml:"view_dir" toml:"view_dir"`
	Database     string `json:"database" yaml:"database" toml:"database"`
	DatabaseConn string `json:"database_conn" yaml:"database_conn" toml:"database_conn"`
}
```

We can Parse ENV to march the field as

ENV|Field
------|--------
APP_NAME| AppName
BASE_URL|BaseURL     
PORT|Port         
VERBOSE|Verbose     
STATIC_DIR|StaticDir    
VIEW_DIR|ViewsDir    
DATABASE|Database     
DATABASE_CONN|DatabaseConn 

This way, we wont need to handcode anything, and the walues will be changed as the `config`` struct change.

Then we can set priority

* ENV
* config file

That way ENV will overide config file values. What do you think?

**Comment by gernest** [comment]
@apaganobeleno we will need a wiki I suppose. To start writing more details, like when we ship this feature.

I am going to work on the code tomorrow if @apaganobeleno and @Gurpartap have no objection. I am waiting for your feedback.

**Comment by Gurpartap** [comment]
Perhaps you can use [vrischmann/envconfig](https://github.com/vrischmann/envconfig) ([example](https://godoc.org/github.com/vrischmann/envconfig#example-Init)).

**Comment by gernest** [comment]
@Gurpartap I have already implemented this in the past, and if you are looking for a better example is https://github.com/koding/multiconfig

Or should we just use this library instead? It does what we are bout to do and does even better see [here](https://github.com/gernest/zedlist/blob/8e2316279017d0f36034b6a645066929431895b5/modules/settings/settings.go#L138) for my previous implementation on [zedlist](https://github.com/gernest/zedlist)] project using `muliconfig`

**Comment by Gurpartap** [comment]
Steer it the way you want it to go.

**Comment by gernest** [comment]
@Gurpartap you suggestion actually fits what we are looking for. I only followed the project like and not read the example.

It fits perfectly.

**Comment by apaganobeleno** [comment]
@gernest i already have it implemented, should i send a PR ?

**Comment by gernest** [comment]
sure @apaganobeleno

**Comment by apaganobeleno** [comment]
@gernest i guest we need some documentation here, do you think is ok to add it into the README.md ? i'm thinking to add something below the configuration section.

**Comment by gernest** [comment]
@apaganobeleno gimme a min so I can review the PR

**Comment by gernest** [comment]
@apaganobeleno can you email me? I want to say something that is a bit private if you don;t mind( It is abiut the PR)

**Comment by apaganobeleno** [comment]
@gernest ok, cool, just emailed you :)
