### ISSUE TITLE
Rename tag 1.0 to v1.0 in order to use gopkg.in

### ISSUE THREAD

**Issue by Slacki** [gernest/utron#53]
As the title says, it would be nice to let users use stable release with `go get` and the easiest way is to use [gopkg.in](http://labix.org/gopkg.in).

With the current tag name `1.0` the service is unable to access 1.0 release. 

```
GitHub repository at https://github.com/gernest/utron has no branch or tag "v1", "v1.N" or "v1.N.M"
```

**Comment by gernest** [comment]
@Slacki thanks, doing that right now

**Comment by gernest** [comment]
@Slacki can you try again? I just fchanged it to v1.0

**Comment by Slacki** [comment]
It works now. I am gonna make a PR later with changes to README and wiki to let users know about this.

**Comment by gernest** [comment]
thanks, I am closing this issue for now.
