### ISSUE TITLE
Use of sessions

### ISSUE THREAD

**Issue by euller88** [gernest/utron#60]
There was I, just browsing some code at Github, when I decided to read Utron's wiki. Then I stumbled upon the middlewares' page, and a doubt was spawned in my head: how the heck I would use this?Do I just have to follow the Gorilla tutorial, or make use of some gimmick to achieve that?

**Comment by gernest** [comment]
Do you have any suggestions on what should be a good way?

**Comment by euller88** [comment]
That's my problem, I'm ashamed to say that I am totally clueless about it. It just amazes me by how long it took for me to realize this.

**Comment by gernest** [comment]
@euller88 great to hear you are on http support. No need to rush, one thing at a time. Thanks.

**Comment by Slacki** [comment]
@euller88 Well, that is my approach. I am newbie to utron and golang itself, so it may be totally wrong and maybe I made a fool of myself. The point was to just do something with session wherever I need sessions (i register this middleware in the controllers I am using sessions in).

**Comment by euller88** [comment]
Well, since utron uses a singleton(cough, cough, baseApp) to handle the whole thing, I think that a general session manager should work, then each controller should create or end one session, and modify it. This is the first idea I had after stopping to think a little

**Comment by OsvaldoTCF** [comment]
perhaps
http://www.alexedwards.net/blog/making-and-using-middleware
