### ISSUE TITLE
Split databaseconnection string into multiple environment variables

### ISSUE THREAD

**Issue by PatWie** [gernest/utron#64]
To use this very nice framwork, I tried to setup docker-compose. RubyOnRails and co use a much easier way to connect to databases, namely environment variables shipped by postgresl:latest container. 

I setup you example inside the docker environment:
https://github.com/PatWie/ultron-webapp-container

However, your library refuses the connection. A dump of available variables are:

```
DB_ENV_POSTGRES_USERNAME=databaseuser
DB_PORT_5432_TCP_ADDR=172.17.0.3
DB_PORT_5403_TCP=tcp://172.17.0.3:5403
DB_PORT=tcp://172.17.0.3:5403
DB_ENV_POSTGRES_PASSWORD=c9aca452d8b439b1e484855a0d4ed105
DB_ENV_LANG=en_US.utf8
DB_ENV_GOSU_VERSION=1.7
DB_PORT_5432_TCP=tcp://172.17.0.3:5432
DB_ENV_PG_MAJOR=9.5
DB_ENV_affinity:container==19e9f7ed42720d5a332c3402fb784276cb2c579e78fc304a28aef7dd1cb1fb72
DB_PORT_5403_TCP_PORT=5403
DB_ENV_POSTGRES_DBNAME=database
DB_PORT_5432_TCP_PROTO=tcp
DB_ENV_PG_VERSION=9.5.4-1.pgdg80+1
DB_PORT_5403_TCP_PROTO=tcp
DB_PORT_5403_TCP_ADDR=172.17.0.3
```

These should be automatically already there. So why not rely on these?

If your framework can be run inside these dockers, it would be an additional argument for using the framework.

The error-message comes from:

```
+ exec app
`` is not officially supported, running under compatibility mode.
2016/09/12 17:23:54 sql: unknown driver "" (forgotten import?)
hipanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x46a68a]

goroutine 1 [running]:
panic(0x8c7ec0, 0xc42000c0a0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/gernest/utron.Run()
	/go/src/github.com/gernest/utron/utron.go:240 +0x3a
main.main()
	/go/src/app/main.go:12 +0xa4

```

which basically belongs to this line
https://github.com/gernest/utron/blob/master/utron.go#L240

**Comment by gernest** [comment]
@PatWie It seems the environment needed by Utron are not provided. You can properly set them in your docker compose file if possible

`DATABASE` states the name of the database i.e `postgres` for  postgresql database `mysql` for mysal database.

`DATABASE_CONN` is a full connection url to the database.

Thanks for bringing this to my attention though. Having something like `UTRON_DATABASE` makes more sense than `DATABASE` perhaps I can use a proper naming scheme.

So can you expand on what you mean by separating database connection string? I mean with maybe example.

**Comment by gernest** [comment]
Another thing, can yopu show me `docker-compose.yml` file? Maybe I can help.

**Comment by PatWie** [comment]
Jus have a look at the repositoy to reproduce everything:
https://github.com/PatWie/ultron-webapp-container

Btw: It would be nice if you support an official example ;-)

**Comment by gernest** [comment]
Okay, I'm going to check it out and then go back to you.

Is there any one in particular that you would like to see me support?

**Comment by PatWie** [comment]
I just want to build boiler template for:
- golang ultron
- postgresql with gorm
- redis

That all ;-) I am right now on gitter.

**Comment by gernest** [comment]
@PatWie Okay, can you ping me on gitter?

**Comment by PatWie** [comment]
A small update:
I added another container "debug" for https://github.com/PatWie/ultron-webapp-container
which basically allows to easily open a bash with all environment variables.

Having all environment variables in place "psql" should be sufficient to fire up the postgres-console. And in golang something like


```
connInfo := fmt.Sprintf(
    "user=%s dbname=%s password=%s host=%s port=%s sslmode=disable",
    os.Getenv("DB_ENV_POSTGRES_USER"),
    os.Getenv("DB_ENV_POSTGRES_DATABASE"),
    os.Getenv("DB_ENV_POSTGRES_PASSWORD"),
    "db",
    os.Getenv("DB_1_PORT_5432_TCP_PORT"),
  )


db, err = sql.Open("postgres", connInfo)
```

should directly work.


This might be also relevant
http://fabioberger.com/post/2014-12-19-how-to-dockerize-golang-webapp-with-postgres-db/

**Comment by gernest** [comment]
@PatWie I fixed the issue and I created a todo list app( from the example) that is can be deployed using docker compose. 

It was fun hooking up the example. I will wait for your feedback before I close this. 

Here is the app https://github.com/gernest/utron-todo

PS: Any help cleaning up the todo app( from the link above) and adding more details on the README will be highly appreciated.
