### ISSUE TITLE
 cannot find package "github.com/gernest/utron/app"

### ISSUE THREAD

**Issue by lchhieu** [gernest/utron#81]
I use win 10 x64, and get error
```
cannot find package "github.com/gernest/utron/app" in any of:
C:\Go\src\github.com\gernest\utron\app (from $GOROOT)
C:\Users\HieuLuong\go\src\github.com\gernest\utron\app (from $GOPATH)
```

**Comment by gernest** [comment]
@lchhieu  try to reinstall utron like this

` go get -v -u github.com/gernest/utron/...`

I don't know why you are seeing such an error but that command should help!

**Comment by gernest** [comment]
Just a reminder sample applications can be found here https://github.com/utronframework

**Comment by lchhieu** [comment]
@gernest i had try again and success

**Comment by gernest** [comment]
Cool! I'm closing this issue then. You can reopen if it still persists.
