### ISSUE TITLE
Secure config

### ISSUE THREAD

**Issue by nicola-spb** [gernest/utron#86]
In **context.go** you send config to view (by default). Users can save passwords and tokens in config file. I think it`s not secure. If user will want to have config in view then he put it himself.

```
if c.Cfg != nil {
	c.Data["Config"] = c.Cfg // add configuration to the view data context
}
```
What do you think?

**Comment by gernest** [comment]
@nicola-spb I think you are right. That is not necessary, the user should be responsible for adding data to be rendered by the templates.

__OFFTOPIC__: Do you mind if I add you to be a maintainer? 

We will still use PR based workflow, and ensure that every PR is reviewed before merging.

**Comment by nicola-spb** [comment]
ok.

**Comment by gernest** [comment]
@nicola-spb nice, just added you. you should receive an invite any moment. Looking forward to making utron awesome with you

**Comment by nicola-spb** [comment]
Ok :-) will try.

**Comment by nicola-spb** [comment]
fixed.

**Comment by gernest** [comment]
@nicola-spb where?

**Comment by gernest** [comment]
@nicola-spb I'm sorry, but I don't think it is a good idea to make changes directly to the master branch without someone to review it.

I suggest we use a PR based approach to run this project. 

These are minor changes so I'm okay with this. But please next time Open a PR, wait until at least one maintainer reviews it( It should not be the one submitting the PR) then when he/she approves you can merge to master.

Thanks.

**Comment by nicola-spb** [comment]
Yes. Sorry. 
I send mail for you to @live.com

**Comment by gernest** [comment]
@nicola-spb no problem. I just saw the email a few mins ago.

We are on a good start.
