### ISSUE TITLE
go get errors

### ISSUE THREAD

**Issue by ross-albertson** [gernest/utron#88]
# github.com/cznic/zappy
exec: "gcc": executable file not found in %PATH%
# github.com/mattn/go-sqlite3
exec: "gcc": executable file not found in %PATH%

**Comment by nicola-spb** [comment]
Sorry, is it utron's error? When you get this error?
P.S. https://stackoverflow.com/questions/43580131/exec-gcc-executable-file-not-found-in-path-when-trying-go-build

**Comment by nicola-spb** [comment]
I close it. You can reopen issue if you think that it`s error of utron.
